services:
  oracle:
    image: gvenzl/oracle-xe:21-slim
    environment:
      ORACLE_PASSWORD: oracle
      ORACLE_DATABASE: XEPDB1
      APP_USER: lms
      APP_USER_PASSWORD: lms
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata

  tomcat:
    image: tomcat:10.1-jdk17
    ports:
      - "8080:8080"
    volumes:
      - ./tomcat/webapps:/usr/local/tomcat/webapps
    depends_on:
      - oracle

  apache:
    image: httpd:2.4
    ports:
      - "80:80"
    volumes:
      - ./apache/httpd-lms.conf.sample:/usr/local/apache2/conf/httpd.conf:ro
    depends_on:
      - tomcat

volumes:
  oracle-data:
