server:
  port: 8080
  address: 0.0.0.0

spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
    username: lms
    password: lms
    driver-class-name: oracle.jdbc.OracleDriver
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    encoding: UTF-8

